# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\DoAnCuoiKy\DoAnCuoiKy\ui\InventoryMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 809)
        MainWindow.setStyleSheet("\n"
"          QFrame {\n"
"              background-color: rgba(255, 255, 255, 0.8);\n"
"              border: 2px solid #99FFDD;\n"
"              border-radius: 10px;\n"
"              margin: 10px;\n"
"          }\n"
"         ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 921, 71))
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color:rgb(0,0,0);\n"
"    margin: 10px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #000000; /* Viền đen */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 361, 651))
        self.frame.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #FF0000; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("\n"
"             QLabel {\n"
"                 font-size: 16px;\n"
"                 font-weight: bold;\n"
"                 margin: 5px;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"             }\n"
"            ")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidgetCategory = QtWidgets.QListWidget(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listWidgetCategory.setFont(font)
        self.listWidgetCategory.setStyleSheet("color:rgb(0,0,0);\n"
"alternate-background-color: rgb(255, 255, 255);\n"
"")
        self.listWidgetCategory.setObjectName("listWidgetCategory")
        self.verticalLayout.addWidget(self.listWidgetCategory)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 90, 381, 661))
        self.frame_2.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #205781; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 321, 51))
        self.label_3.setStyleSheet("color: rgb(0,0,0);")
        self.label_3.setObjectName("label_3")
        self.tableWidgetProduct = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tableWidgetProduct.setGeometry(QtCore.QRect(20, 70, 341, 571))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidgetProduct.setFont(font)
        self.tableWidgetProduct.setStyleSheet("color:rgb(0,0,0)")
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(0)
        self.tableWidgetProduct.setRowCount(0)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(740, 90, 411, 661))
        self.frame_3.setStyleSheet("QFrame {\n"
"   \n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid #353924; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 351, 101))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"             QLabel {\n"
"                 font-size: 16px;\n"
"                 font-weight: bold;\n"
"                 margin: 5px;\n"
"color:rgb(0,0,0)\n"
"             }\n"
"            ")
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 371, 311))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0,0,0)")
        self.label_5.setObjectName("label_5")
        self.lineEditProID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditProID.setGeometry(QtCore.QRect(130, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditProID.setFont(font)
        self.lineEditProID.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #353924; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */;\n"
"color:rgb(0,0,0)\n"
"}")
        self.lineEditProID.setObjectName("lineEditProID")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(0,0,0)")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(0, 140, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0,0,0)")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(0, 200, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0,0,0)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(0, 250, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0,0,0)")
        self.label_9.setObjectName("label_9")
        self.lineEditProName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditProName.setGeometry(QtCore.QRect(130, 90, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditProName.setFont(font)
        self.lineEditProName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #353924; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */;\n"
"color:rgb(0,0,0)\n"
"}")
        self.lineEditProName.setObjectName("lineEditProName")
        self.lineEditPrice = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPrice.setGeometry(QtCore.QRect(130, 150, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditPrice.setFont(font)
        self.lineEditPrice.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #353924; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */;\n"
"color:rgb(0,0,0)\n"
"}")
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditQuantity.setGeometry(QtCore.QRect(130, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditQuantity.setFont(font)
        self.lineEditQuantity.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #353924; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */;\n"
"color:rgb(0,0,0)\n"
"}")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.lineEditCateID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditCateID.setGeometry(QtCore.QRect(130, 260, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEditCateID.setFont(font)
        self.lineEditCateID.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #353924; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */;\n"
"color:rgb(0,0,0)\n"
"}")
        self.lineEditCateID.setObjectName("lineEditCateID")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonNew.setGeometry(QtCore.QRect(40, 450, 331, 41))
        self.pushButtonNew.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"                 background-color: #FFC374;\n"
"                 color:rgb(0,0,0);\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #FFC374;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #497D74;\n"
"             }")
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonAddProduct = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonAddProduct.setGeometry(QtCore.QRect(40, 500, 331, 41))
        self.pushButtonAddProduct.setStyleSheet("QPushButton {\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"                 background-color: #A7D0D6;\n"
"                 color:rgb(0,0,0);\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #A7D0D6;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #A7D0D6;\n"
"             }")
        self.pushButtonAddProduct.setObjectName("pushButtonAddProduct")
        self.pushButtonRemoveProduct = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonRemoveProduct.setGeometry(QtCore.QRect(40, 550, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonRemoveProduct.setFont(font)
        self.pushButtonRemoveProduct.setStyleSheet("\n"
"             QPushButton {\n"
"                 background-color: #FF6666;\n"
"                 color: black;\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #FF3333;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #CC0000;\n"
"             }\n"
"            ")
        self.pushButtonRemoveProduct.setObjectName("pushButtonRemoveProduct")
        self.pushButtonCloseInventory = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButtonCloseInventory.setGeometry(QtCore.QRect(40, 600, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCloseInventory.setFont(font)
        self.pushButtonCloseInventory.setStyleSheet("\n"
"             QPushButton {\n"
"                 background-color: #CCCCCC;\n"
"                 \n"
"    color: rgb(0, 0, 0);\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #AAAAAA;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #888888;\n"
"             }\n"
"            ")
        self.pushButtonCloseInventory.setObjectName("pushButtonCloseInventory")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inventory_MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Màn hình  quản lý kho</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Danh mục</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Bảng tồn kho</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Thông tin sản phẩm</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Mã sản phẩm:"))
        self.label_6.setText(_translate("MainWindow", "Tên sản phẩm:"))
        self.label_7.setText(_translate("MainWindow", "Giá:"))
        self.label_8.setText(_translate("MainWindow", "Số lượng:"))
        self.label_9.setText(_translate("MainWindow", "Mã danh mục:"))
        self.pushButtonNew.setText(_translate("MainWindow", "New"))
        self.pushButtonAddProduct.setText(_translate("MainWindow", "Add"))
        self.pushButtonRemoveProduct.setText(_translate("MainWindow", "Remove"))
        self.pushButtonCloseInventory.setText(_translate("MainWindow", "Close"))
