# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\DoAnCuoiKy\DoAnCuoiKy\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1143, 755)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 1111, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Kĩ Thuật Lập Trình\\ĐoAnCuoiKy\\DoAnCuoiKy\\DoAnCuoiKy\\ui\\../../../../../Download/Thiết kế chưa có tên.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(660, 130, 411, 471))
        self.frame.setStyleSheet("background-color: #686D76;\n"
" border-radius: 20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 391, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 15px;\n"
"color: rgb(0,0,0);\n"
"border: 2px solid black;\n"
"")
        self.label_2.setObjectName("label_2")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUserName.setGeometry(QtCore.QRect(20, 130, 361, 41))
        self.lineEditUserName.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassword.setGeometry(QtCore.QRect(20, 220, 361, 41))
        self.lineEditPassword.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.radioButtonStaff = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButtonStaff.setGeometry(QtCore.QRect(70, 290, 81, 31))
        self.radioButtonStaff.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: rgb(0,0,0)")
        self.radioButtonStaff.setObjectName("radioButtonStaff")
        self.radioButtonManager = QtWidgets.QRadioButton(parent=self.frame)
        self.radioButtonManager.setGeometry(QtCore.QRect(230, 290, 111, 31))
        self.radioButtonManager.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"font: 13pt \".AppleSystemUIFont\";\n"
"border-color: rgb(255, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"color: rgb(0,0,0)")
        self.radioButtonManager.setObjectName("radioButtonManager")
        self.checkBoxSavePassWord = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxSavePassWord.setGeometry(QtCore.QRect(120, 340, 171, 31))
        self.checkBoxSavePassWord.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0,0,0)\n"
"")
        self.checkBoxSavePassWord.setObjectName("checkBoxSavePassWord")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 100, 81, 21))
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 81, 21))
        self.label_7.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLogin.setGeometry(QtCore.QRect(20, 390, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("\n"
"       QPushButton {\n"
"           background-color: #FE7E6D;\n"
"\n"
"            color: rgb(255, 255, 255);\n"
"           border: 2px solid #FF9999;\n"
"           border-radius: 15px;\n"
"           font: bold 14pt;\n"
"       }\n"
"       QPushButton:hover {\n"
"           background-color: #FE7E6D;\n"
"       }\n"
"       QPushButton:pressed {\n"
"           background-color: #FE7E6D;\n"
"       }\n"
"      ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Kĩ Thuật Lập Trình\\ĐoAnCuoiKy\\DoAnCuoiKy\\DoAnCuoiKy\\ui\\../../../Download/8679838_login_box_line_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonExit.setGeometry(QtCore.QRect(220, 390, 161, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("\n"
"       QPushButton {\n"
"           background-color: #FE7E6D;\n"
"\n"
"            color: rgb(255, 255, 255);\n"
"           border: 2px solid #FF9999;\n"
"           border-radius: 15px;\n"
"           font: bold 14pt;\n"
"       }\n"
"       QPushButton:hover {\n"
"           background-color: #FE7E6D;\n"
"       }\n"
"       QPushButton:pressed {\n"
"           background-color: #FE7E6D;\n"
"       }\n"
"      ")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Kĩ Thuật Lập Trình\\ĐoAnCuoiKy\\DoAnCuoiKy\\DoAnCuoiKy\\ui\\../../../Download/3994382_access_close_exit_logout_sign out_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon1)
        self.pushButtonExit.setObjectName("pushButtonExit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1143, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login_MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Login</span></p></body></html>"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Đăng nhập ngay thôii ...."))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Mật khẩu nè ...."))
        self.radioButtonStaff.setText(_translate("MainWindow", "Staff"))
        self.radioButtonManager.setText(_translate("MainWindow", "Manager"))
        self.checkBoxSavePassWord.setText(_translate("MainWindow", "Save Password"))
        self.label_6.setText(_translate("MainWindow", " Đăng nhập:"))
        self.label_7.setText(_translate("MainWindow", " Mật khẩu:"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.pushButtonExit.setText(_translate("MainWindow", "Thoát"))
