# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\Test\ui\InventoryMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InventoryUltimateWindow(object):
    def setupUi(self, InventoryUltimateWindow):
        InventoryUltimateWindow.setObjectName("InventoryUltimateWindow")
        InventoryUltimateWindow.resize(1200, 700)
        InventoryUltimateWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        background-image: url(:/images/inventory_background.png);\n"
"        background-position: center;\n"
"        background-repeat: no-repeat;\n"
"        background-color: #E6FFFA;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=InventoryUltimateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.frameCategories = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameCategories.setMinimumSize(QtCore.QSize(200, 0))
        self.frameCategories.setStyleSheet("\n"
"        QFrame {\n"
"            background-color: rgba(255, 255, 255, 0.8);\n"
"            border-radius: 10px;\n"
"            margin: 10px;\n"
"        }\n"
"       ")
        self.frameCategories.setObjectName("frameCategories")
        self.verticalLayout_categories = QtWidgets.QVBoxLayout(self.frameCategories)
        self.verticalLayout_categories.setObjectName("verticalLayout_categories")
        self.labelCategoryTitle = QtWidgets.QLabel(parent=self.frameCategories)
        self.labelCategoryTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelCategoryTitle.setStyleSheet("\n"
"           QLabel {\n"
"               font-size: 16px;\n"
"               font-weight: bold;\n"
"               margin: 5px;\n"
"           }\n"
"          ")
        self.labelCategoryTitle.setObjectName("labelCategoryTitle")
        self.verticalLayout_categories.addWidget(self.labelCategoryTitle)
        self.listWidgetCategories = QtWidgets.QListWidget(parent=self.frameCategories)
        self.listWidgetCategories.setStyleSheet("\n"
"           QListWidget {\n"
"               background-color: #CCFFEE;\n"
"               border: 1px solid #99FFDD;\n"
"               border-radius: 5px;\n"
"               padding: 5px;\n"
"           }\n"
"           QListWidget::item:selected {\n"
"               background-color: #33CC99;\n"
"               color: white;\n"
"           }\n"
"          ")
        self.listWidgetCategories.setObjectName("listWidgetCategories")
        self.verticalLayout_categories.addWidget(self.listWidgetCategories)
        self.horizontalLayout_main.addWidget(self.frameCategories)
        self.tableWidgetInventory = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetInventory.setColumnCount(5)
        self.tableWidgetInventory.setHorizontalHeaderLabels(['Mã SP', 'Tên SP', 'Giá', 'Số lượng', 'Danh mục'])
        self.tableWidgetInventory.setStyleSheet("\n"
"        QTableWidget {\n"
"            background-color: #FFFFFF;\n"
"            gridline-color: #AAAAAA;\n"
"            border: 1px solid #CCCCCC;\n"
"        }\n"
"        QHeaderView::section {\n"
"            background-color: #99FFDD;\n"
"            font-weight: bold;\n"
"        }\n"
"       ")
        self.tableWidgetInventory.setObjectName("tableWidgetInventory")
        self.tableWidgetInventory.setRowCount(0)
        self.horizontalLayout_main.addWidget(self.tableWidgetInventory)
        self.frameInfo = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameInfo.setMinimumSize(QtCore.QSize(300, 0))
        self.frameInfo.setStyleSheet("\n"
"        QFrame {\n"
"            background-color: rgba(255, 255, 255, 0.9);\n"
"            border-radius: 10px;\n"
"            margin: 10px;\n"
"        }\n"
"       ")
        self.frameInfo.setObjectName("frameInfo")
        self.verticalLayout_info = QtWidgets.QVBoxLayout(self.frameInfo)
        self.verticalLayout_info.setObjectName("verticalLayout_info")
        self.labelInfoTitle = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelInfoTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelInfoTitle.setStyleSheet("\n"
"           QLabel {\n"
"               font-size: 16px;\n"
"               font-weight: bold;\n"
"               margin: 5px;\n"
"           }\n"
"          ")
        self.labelInfoTitle.setObjectName("labelInfoTitle")
        self.verticalLayout_info.addWidget(self.labelInfoTitle)
        self.formLayoutInfo = QtWidgets.QFormLayout()
        self.formLayoutInfo.setObjectName("formLayoutInfo")
        self.labelCode = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelCode.setObjectName("labelCode")
        self.formLayoutInfo.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelCode)
        self.lineEditCode = QtWidgets.QLineEdit(parent=self.frameInfo)
        self.lineEditCode.setObjectName("lineEditCode")
        self.formLayoutInfo.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditCode)
        self.labelName = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelName.setObjectName("labelName")
        self.formLayoutInfo.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.frameInfo)
        self.lineEditName.setObjectName("lineEditName")
        self.formLayoutInfo.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditName)
        self.labelPrice = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelPrice.setObjectName("labelPrice")
        self.formLayoutInfo.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPrice)
        self.lineEditPrice = QtWidgets.QLineEdit(parent=self.frameInfo)
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.formLayoutInfo.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditPrice)
        self.labelQuantity = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelQuantity.setObjectName("labelQuantity")
        self.formLayoutInfo.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelQuantity)
        self.lineEditQuantity = QtWidgets.QLineEdit(parent=self.frameInfo)
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.formLayoutInfo.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditQuantity)
        self.labelCategory = QtWidgets.QLabel(parent=self.frameInfo)
        self.labelCategory.setObjectName("labelCategory")
        self.formLayoutInfo.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelCategory)
        self.lineEditCategory = QtWidgets.QLineEdit(parent=self.frameInfo)
        self.lineEditCategory.setObjectName("lineEditCategory")
        self.formLayoutInfo.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditCategory)
        self.verticalLayout_info.addLayout(self.formLayoutInfo)
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.frameInfo)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon_newsale.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNew.setIcon(icon)
        self.pushButtonNew.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #33CC99;\n"
"               color: white;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #2FAE85;\n"
"           }\n"
"          ")
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.verticalLayout_info.addWidget(self.pushButtonNew)
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.frameInfo)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icon_add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonAdd.setIcon(icon1)
        self.pushButtonAdd.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #33CC99;\n"
"               color: white;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #2FAE85;\n"
"           }\n"
"          ")
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout_info.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(parent=self.frameInfo)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icon_remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRemove.setIcon(icon2)
        self.pushButtonRemove.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #FF6666;\n"
"               color: white;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #FF3333;\n"
"           }\n"
"          ")
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.verticalLayout_info.addWidget(self.pushButtonRemove)
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.frameInfo)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icon_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClose.setIcon(icon3)
        self.pushButtonClose.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #CCCCCC;\n"
"               color: black;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #AAAAAA;\n"
"           }\n"
"          ")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.verticalLayout_info.addWidget(self.pushButtonClose)
        self.horizontalLayout_main.addWidget(self.frameInfo)
        InventoryUltimateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(InventoryUltimateWindow)
        QtCore.QMetaObject.connectSlotsByName(InventoryUltimateWindow)

    def retranslateUi(self, InventoryUltimateWindow):
        _translate = QtCore.QCoreApplication.translate
        InventoryUltimateWindow.setWindowTitle(_translate("InventoryUltimateWindow", "Inventory - Ultimate"))
        self.labelCategoryTitle.setText(_translate("InventoryUltimateWindow", "Danh mục"))
        self.labelInfoTitle.setText(_translate("InventoryUltimateWindow", "Thông tin sản phẩm"))
        self.labelCode.setText(_translate("InventoryUltimateWindow", "Mã sản phẩm:"))
        self.labelName.setText(_translate("InventoryUltimateWindow", "Tên sản phẩm:"))
        self.labelPrice.setText(_translate("InventoryUltimateWindow", "Giá:"))
        self.labelQuantity.setText(_translate("InventoryUltimateWindow", "Số lượng:"))
        self.labelCategory.setText(_translate("InventoryUltimateWindow", "Mã danh mục:"))
        self.pushButtonNew.setText(_translate("InventoryUltimateWindow", "New"))
        self.pushButtonAdd.setText(_translate("InventoryUltimateWindow", "Add"))
        self.pushButtonRemove.setText(_translate("InventoryUltimateWindow", "Remove"))
        self.pushButtonClose.setText(_translate("InventoryUltimateWindow", "Close"))
