# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\Test\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginUltimateWindow(object):
    def setupUi(self, LoginUltimateWindow):
        LoginUltimateWindow.setObjectName("LoginUltimateWindow")
        LoginUltimateWindow.resize(600, 400)
        LoginUltimateWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        /* Ảnh nền login */\n"
"        background-image: url(:/images/background_login.png);\n"
"        background-position: center;\n"
"        background-repeat: no-repeat;\n"
"        background-color: #F8F8F8; /* fallback nếu ảnh không load */\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=LoginUltimateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_header.addItem(spacerItem)
        self.labelLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelLogo.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setMaximumSize(QtCore.QSize(120, 120))
        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout_header.addWidget(self.labelLogo)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_header.addItem(spacerItem1)
        self.verticalLayout_main.addLayout(self.horizontalLayout_header)
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelTitle.setStyleSheet("\n"
"        QLabel {\n"
"            font-size: 20px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"        }\n"
"       ")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_main.addWidget(self.labelTitle)
        self.frameLogin = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameLogin.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLogin.setStyleSheet("\n"
"        QFrame {\n"
"            background-color: rgba(255, 255, 255, 0.8);\n"
"            border-radius: 10px;\n"
"            margin: 20px;\n"
"        }\n"
"       ")
        self.frameLogin.setObjectName("frameLogin")
        self.verticalLayout_frame = QtWidgets.QVBoxLayout(self.frameLogin)
        self.verticalLayout_frame.setObjectName("verticalLayout_frame")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frameLogin)
        self.lineEditUsername.setStyleSheet("\n"
"           QLineEdit {\n"
"               border: 1px solid #CCCCCC;\n"
"               border-radius: 5px;\n"
"               padding: 5px;\n"
"           }\n"
"           QLineEdit:focus {\n"
"               border: 1px solid #6666FF;\n"
"           }\n"
"          ")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_frame.addWidget(self.lineEditUsername)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frameLogin)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setStyleSheet("\n"
"           QLineEdit {\n"
"               border: 1px solid #CCCCCC;\n"
"               border-radius: 5px;\n"
"               padding: 5px;\n"
"           }\n"
"           QLineEdit:focus {\n"
"               border: 1px solid #6666FF;\n"
"           }\n"
"          ")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_frame.addWidget(self.lineEditPassword)
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frameLogin)
        self.pushButtonLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonLogin.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #3399FF;\n"
"               color: white;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"               font-weight: bold;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #1A8CFF;\n"
"           }\n"
"          ")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.verticalLayout_frame.addWidget(self.pushButtonLogin)
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frameLogin)
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #EEEEEE;\n"
"               color: #333333;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #DDDDDD;\n"
"           }\n"
"          ")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_frame.addWidget(self.pushButtonExit)
        self.verticalLayout_main.addWidget(self.frameLogin)
        LoginUltimateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginUltimateWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginUltimateWindow)

    def retranslateUi(self, LoginUltimateWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginUltimateWindow.setWindowTitle(_translate("LoginUltimateWindow", "Login - Ultimate"))
        self.labelTitle.setText(_translate("LoginUltimateWindow", "ĐĂNG NHẬP HỆ THỐNG"))
        self.lineEditUsername.setPlaceholderText(_translate("LoginUltimateWindow", "Tên đăng nhập..."))
        self.lineEditPassword.setPlaceholderText(_translate("LoginUltimateWindow", "Mật khẩu..."))
        self.pushButtonLogin.setText(_translate("LoginUltimateWindow", "Đăng nhập"))
        self.pushButtonExit.setText(_translate("LoginUltimateWindow", "Thoát"))
# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\Test\ui\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginUltimateWindow(object):
    def setupUi(self, LoginUltimateWindow):
        LoginUltimateWindow.setObjectName("LoginUltimateWindow")
        LoginUltimateWindow.resize(600, 400)
        LoginUltimateWindow.setStyleSheet("\n"
"    QMainWindow {\n"
"        /* Ảnh nền login */\n"
"        background-image: url(:/images/background_login.png);\n"
"        background-position: center;\n"
"        background-repeat: no-repeat;\n"
"        background-color: #F8F8F8; /* fallback nếu ảnh không load */\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=LoginUltimateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_header = QtWidgets.QHBoxLayout()
        self.horizontalLayout_header.setObjectName("horizontalLayout_header")
        spacerItem = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_header.addItem(spacerItem)
        self.labelLogo = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelLogo.setPixmap(QtGui.QPixmap(":/images/logo.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setMaximumSize(QtCore.QSize(120, 120))
        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout_header.addWidget(self.labelLogo)
        spacerItem1 = QtWidgets.QSpacerItem(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.horizontalLayout_header.addItem(spacerItem1)
        self.verticalLayout_main.addLayout(self.horizontalLayout_header)
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelTitle.setStyleSheet("\n"
"        QLabel {\n"
"            font-size: 20px;\n"
"            font-weight: bold;\n"
"            color: #333333;\n"
"        }\n"
"       ")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_main.addWidget(self.labelTitle)
        self.frameLogin = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameLogin.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameLogin.setStyleSheet("\n"
"        QFrame {\n"
"            background-color: rgba(255, 255, 255, 0.8);\n"
"            border-radius: 10px;\n"
"            margin: 20px;\n"
"        }\n"
"       ")
        self.frameLogin.setObjectName("frameLogin")
        self.verticalLayout_frame = QtWidgets.QVBoxLayout(self.frameLogin)
        self.verticalLayout_frame.setObjectName("verticalLayout_frame")
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.frameLogin)
        self.lineEditUsername.setStyleSheet("\n"
"           QLineEdit {\n"
"               border: 1px solid #CCCCCC;\n"
"               border-radius: 5px;\n"
"               padding: 5px;\n"
"           }\n"
"           QLineEdit:focus {\n"
"               border: 1px solid #6666FF;\n"
"           }\n"
"          ")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_frame.addWidget(self.lineEditUsername)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frameLogin)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setStyleSheet("\n"
"           QLineEdit {\n"
"               border: 1px solid #CCCCCC;\n"
"               border-radius: 5px;\n"
"               padding: 5px;\n"
"           }\n"
"           QLineEdit:focus {\n"
"               border: 1px solid #6666FF;\n"
"           }\n"
"          ")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_frame.addWidget(self.lineEditPassword)
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frameLogin)
        self.pushButtonLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonLogin.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #3399FF;\n"
"               color: white;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"               font-weight: bold;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #1A8CFF;\n"
"           }\n"
"          ")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.verticalLayout_frame.addWidget(self.pushButtonLogin)
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.frameLogin)
        self.pushButtonExit.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButtonExit.setStyleSheet("\n"
"           QPushButton {\n"
"               background-color: #EEEEEE;\n"
"               color: #333333;\n"
"               border-radius: 5px;\n"
"               padding: 8px;\n"
"           }\n"
"           QPushButton:hover {\n"
"               background-color: #DDDDDD;\n"
"           }\n"
"          ")
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.verticalLayout_frame.addWidget(self.pushButtonExit)
        self.verticalLayout_main.addWidget(self.frameLogin)
        LoginUltimateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginUltimateWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginUltimateWindow)

    def retranslateUi(self, LoginUltimateWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginUltimateWindow.setWindowTitle(_translate("LoginUltimateWindow", "Login - Ultimate"))
        self.labelTitle.setText(_translate("LoginUltimateWindow", "ĐĂNG NHẬP HỆ THỐNG"))
        self.lineEditUsername.setPlaceholderText(_translate("LoginUltimateWindow", "Tên đăng nhập..."))
        self.lineEditPassword.setPlaceholderText(_translate("LoginUltimateWindow", "Mật khẩu..."))
        self.pushButtonLogin.setText(_translate("LoginUltimateWindow", "Đăng nhập"))
        self.pushButtonExit.setText(_translate("LoginUltimateWindow", "Thoát"))
