# Form implementation generated from reading ui file 'D:\Kĩ Thuật Lập Trình\ĐoAnCuoiKy\ui\InventoryMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 809)
        MainWindow.setStyleSheet("\n"
"          QFrame {\n"
"              background-color: rgba(255, 255, 255, 0.8);\n"
"              border: 2px solid #99FFDD;\n"
"              border-radius: 10px;\n"
"              margin: 10px;\n"
"          }\n"
"         ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 921, 71))
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #444444;\n"
"    margin: 10px;\n"
"    background-color: rgba(255,255,255,0.6);\n"
"    border-radius: 10px;\n"
"    padding: 5px 10px;\n"
"    border: 2px solid #000000; /* Viền đen */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 90, 361, 651))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    border: 2px solid #FF0000; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"             QLabel {\n"
"                 font-size: 16px;\n"
"                 font-weight: bold;\n"
"                 margin: 5px;\n"
"             }\n"
"            ")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget = QtWidgets.QListWidget(parent=self.frame)
        self.listWidget.setStyleSheet("background-color: rgb(255, 34, 14);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(227, 0, 0);")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(360, 90, 381, 661))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    border: 2px solid #205781; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 321, 61))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 341, 561))
        self.tableWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(740, 90, 411, 661))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 0.8);\n"
"    border: 2px solid #EFB036; /* Màu đỏ */\n"
"    border-radius: 10px;\n"
"    margin: 10px;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 351, 101))
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"             QLabel {\n"
"                 font-size: 16px;\n"
"                 font-weight: bold;\n"
"                 margin: 5px;\n"
"             }\n"
"            ")
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 130, 371, 311))
        self.groupBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 121, 51))
        self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(130, 30, 221, 31))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #FFD700; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 80, 121, 51))
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(0, 140, 71, 51))
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(0, 200, 121, 51))
        self.label_8.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(0, 250, 121, 51))
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 90, 221, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #FFD700; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 150, 221, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    color: rgb(0, 0, 0);\n"
"    border: 2px solid #FFD700; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 210, 221, 31))
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #FFD700; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(130, 260, 221, 31))
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #FFD700; /* #FFD700 là mã màu vàng (Gold) */\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* nền trắng */\n"
"}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(40, 450, 331, 41))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"                 background-color: #FFC374;\n"
"                 color: black;\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #FFC374;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #497D74;\n"
"             }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 500, 331, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 0, 0);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"                 background-color: #FFC374;\n"
"                 color: black;\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #FFC374;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #497D74;\n"
"             }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 550, 331, 41))
        self.pushButton_3.setStyleSheet("\n"
"             QPushButton {\n"
"                 background-color: #FF6666;\n"
"                 color: white;\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #FF3333;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #CC0000;\n"
"             }\n"
"            ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 600, 331, 41))
        self.pushButton_4.setStyleSheet("\n"
"             QPushButton {\n"
"                 background-color: #CCCCCC;\n"
"                 color: black;\n"
"                 border-radius: 5px;\n"
"                 padding: 8px;\n"
"             }\n"
"             QPushButton:hover {\n"
"                 background-color: #AAAAAA;\n"
"             }\n"
"             QPushButton:pressed {\n"
"                 background-color: #888888;\n"
"             }\n"
"            ")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Màn hình  quản lý kho</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Danh mục</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Bảng tồn kho</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Thông tin sản phẩm</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Mã sản phẩm:"))
        self.label_6.setText(_translate("MainWindow", "Tên sản phẩm:"))
        self.label_7.setText(_translate("MainWindow", "Gía:"))
        self.label_8.setText(_translate("MainWindow", "Số lượng"))
        self.label_9.setText(_translate("MainWindow", "Mã danh mục"))
        self.pushButton.setText(_translate("MainWindow", "New"))
        self.pushButton_2.setText(_translate("MainWindow", "Add"))
        self.pushButton_3.setText(_translate("MainWindow", "Remove"))
        self.pushButton_4.setText(_translate("MainWindow", "Close"))
